// USER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_REQUEST_SUCCESSFUL = 'REGISTER_REQUEST_SUCCESSFUL';
export const REGISTER_REQUEST_FAILURE = 'REGISTER_REQUEST_FAILURE';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_REQUEST_SUCCESSFUL = 'AUTH_REQUEST_SUCCESSFUL';
export const AUTH_REQUEST_FAILURE = 'AUTH_REQUEST_FAILURE';
export const DOCUMENT_TYPE_REQUEST = 'DOCUMENT_TYPE_REQUEST';
export const DOCUMENT_TYPE_REQUEST_SUCCESSFUL =
  'DOCUMENT_TYPE_REQUEST_SUCCESSFUL';
export const DOCUMENT_TYPE_REQUEST_FAILURE = 'DOCUMENT_TYPE_REQUEST_FAILURE';
export const SET_TOKEN = 'SET_TOKEN';
export const GET_USER_REQUEST_SUCCESSFUL = 'GET_USER_REQUEST_SUCCESSFUL';
export const GET_USER_REQUEST_FAILURE = 'GET_USER_REQUEST_FAILURE';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const UPDATE_USER_REQUEST_SUCCESSFUL = 'UPDATE_USER_REQUEST_SUCCESSFUL';
export const UPDATE_USER_REQUEST_FAILURE = 'UPDATE_USER_REQUEST_FAILURE';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';

//UPLOAD IMAGE
export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_REQUEST_SUCCESSFUL =
  'UPLOAD_IMAGE_REQUEST_SUCCESSFUL';
export const UPLOAD_IMAGE_REQUEST_FAILURE = 'UPLOAD_IMAGE_REQUEST_FAILURE';

// VEHICLE_REQUEST
export const GET_VEHICLE_REQUEST = 'GET_VEHICLE_REQUEST';
export const GET_VEHICLE_REQUEST_SUCCESSFUL = 'GET_VEHICLE_REQUEST_SUCCESSFUL';
export const GET_VEHICLE_REQUEST_FAILURE = 'GET_VEHICLE_REQUEST_FAILURE';
export const CREATE_VEHICLE_REQUEST = 'CREATE_VEHICLE_REQUEST';
export const CREATE_VEHICLE_REQUEST_SUCCESSFUL =
  'CREATE_VEHICLE_REQUEST_SUCCESFUL';
export const CREATE_VEHICLE_REQUEST_FAILURE = 'CREATE_VEHICLE_REQUEST_FAILURE';
export const GET_VEHICLE_TYPES_REQUEST = 'GET_VEHICLE_TYPES_REQUEST';
export const GET_VEHICLE_TYPES_REQUEST_SUCCESSFUL =
  'GET_VEHICLE_TYPES_REQUEST_SUCCESSFUL';
export const GET_VEHICLE_TYPES_REQUEST_FAILURE =
  'GET_VEHICLE_TYPES_REQUEST_FAILURE';

// TRAVELS
export const GET_TRAVELS_REQUEST = 'GET_TRAVELS_REQUEST';
export const GET_TRAVELS_REQUEST_FAILURE = 'GET_TRAVELS_REQUEST_FAILURE';
export const GET_TRAVELS_REQUEST_SUCCESSFUL = 'GET_TRAVELS_REQUEST_SUCCESSFUL';
export const GET_TRAVELS_DETAIL_REQUEST = 'GET_TRAVELS_DETAIL_REQUEST';
export const GET_TRAVELS_DETAIL_REQUEST_FAILURE =
  'GET_TRAVELS_DETAIL_REQUEST_FAILURE';
export const GET_TRAVELS_DETAIL_REQUEST_SUCCESSFUL =
  'GET_TRAVELS_DETAIL_REQUEST_SUCCESSFUL';
export const UPDATE_TRAVEL_REQUEST = 'UPDATE_TRAVEL_REQUEST';
export const UPDATE_TRAVEL_REQUEST_FAILURE = 'UPDATE_TRAVEL_REQUEST_FAILURE';
export const UPDATE_TRAVEL_REQUEST_SUCCESSFUL =
  'UPDATE_TRAVEL_REQUEST_SUCCESSFUL';
export const GET_HISTORY_REQUEST = 'GET_HISTORY_REQUEST';
export const GET_HISTORY_REQUEST_SUCCESSFUL = 'GET_HISTORY_REQUEST_SUCCESSFUL';
export const GET_HISTORY_REQUEST_FAILURE = 'GET_HISTORY_REQUEST_FAILURE';
export const GET_TRAVELS_TYPE_REQUEST = 'GET_TRAVELS_TYPE_REQUEST';
export const GET_TRAVELS_TYPE_REQUEST_SUCCESSFUL =
  'GET_TRAVELS_TYPE_REQUEST_SUCCESSFUL';
export const GET_TRAVELS_TYPE_REQUEST_FAILURE =
  'GET_TRAVELS_TYPE_REQUEST_FAILURE';
export const GET_TRAVEL_ACTIVE_REQUEST = 'GET_TRAVEL_ACTIVE_REQUEST';
export const GET_TRAVEL_ACTIVE_REQUEST_SUCCESSFUL =
  'GET_TRAVEL_ACTIVE_REQUEST_SUCCESSFUL';
export const GET_TRAVEL_ACTIVE_REQUEST_FAILURE =
  'GET_TRAVEL_ACTIVE_REQUEST_FAILURE';
export const RESET_ACTIVE_TRAVEL = 'RESET_ACTIVE_TRAVEL';
