// USER
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESFUL = 'LOGIN_REQUEST_SUCCESFUL';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_REQUEST_SUCCESFUL = 'SIGNUP_REQUEST_SUCCESFUL';
export const SIGNUP_REQUEST_FAILURE = 'SIGNUP_REQUEST_FAILURE';